version: "3"
services:
    # IMPORTANT, NAME HOST IN .env THE SAME AS THE SERVICE NAME HERE, IN THIS CASE MYSQL
    mysql-rca:
        container_name: mysql-rca #container name should not conflict with existing containers/images
        image: mysql:5.7
        ports:
             - '3312:3306'
        environment:
             - MYSQL_ROOT_PASSWORD=root
             - MYSQL_DATABASE=react_laravel_websockets
             - MYSQL_USER=admin
             - MYSQL_PASSWORD=123456
        volumes:
             - './bin:/docker-entrypoint-initdb.d/'
    main:
        container_name: main
        hostname: main
        build:
            context: .
            dockerfile: dockerfile
        ports:
            - "3000:3000" # Main App
            - "6001:6001" # Websocket server
        volumes:
            - .:/main
            - /main/node_modules # empty node_modules folder, npm cannot create folder in container build,reason unknown
            - /main/vendor # empty vendor folder, composer create folder in container build,reason unknown
        command: sh -c "php artisan key:generate && php artisan passport:install && php artisan migrate && npm run all"
   
networks:
    default:
        external:
            name: nginxrpgateway_default
