version: "3"
services:
    main:
        container_name: main
        hostname: main
        build:
            context: .
            dockerfile: dockerfile
        ports:
            - "3000:3000"
        volumes:
            - .:/app
            # - /main/node_modules
            # - /main/vendor
    mysql:
        container_name: mysql
        image: mysql:5.7
        ports:
             - '3312:3306'
        environment:
             - MYSQL_ROOT_PASSWORD=root
             - MYSQL_DATABASE=react_laravel_websockets
             - MYSQL_USER=root
             - MYSQL_PASSWORD=123456
        volumes:
             - './bin:/docker-entrypoint-initdb.d/'
             - ./mysql-data:/var/lib/mysql
# networks:
#     default:
#         external:
#             name: nginxrpgateway_default
