version: "3"
services:
    # IMPORTANT, NAME HOST IN .env THE SAME AS THE SERVICE NAME HERE, IN THIS CASE MYSQL
    mysql-rca:
        container_name: mysql-rca #container name should not conflict with existing containers/images
        image: mysql:5.7
        ports:
             - '3315:3306'
        environment:
             - MYSQL_ROOT_PASSWORD=root
             - MYSQL_DATABASE=react_laravel_websockets
             - MYSQL_USER=admin
             - MYSQL_PASSWORD=123456
        volumes:
             - './bin:/docker-entrypoint-initdb.d/'
    main:
        container_name: main
        # hostname: main
        depends_on:
            - mysql-rca
        build:
            context: .
            dockerfile: dockerfile
        restart: unless-stopped
        ports:
            - "9000:9000" # Main App
            - "6001:6001" # Websocket server
        volumes:
            - .:/var/www
            - /var/www/node_modules # empty node_modules folder, npm cannot create folder in container build,reason unknown
            - /var/www/vendor # empty vendor folder, composer create folder in container build,reason unknown
        command: sh -c "php artisan key:generate && php artisan passport:install && php artisan migrate && php-fpm -D && npm run prod"
        
    nginx: 
        image: nginx:alpine
        container_name: nginx_laravel
        restart: unless-stopped
        ports: 
            - "8000:8000"
        volumes:
            - './:/var/www'
            - './nginx:/etc/nginx/conf.d/'
        depends_on:
            -  main
networks:
    default:
        external:
            name: nginxrpgateway_default
