version: "3"
services:
    mysql:
        container_name: mysql
        image: mysql:5.7
        ports:
             - '3306:3306'
        environment:
             - MYSQL_ROOT_PASSWORD=root
             - MYSQL_DATABASE=react_laravel_websockets
             - MYSQL_USER=admin
             - MYSQL_PASSWORD=123456
    main:
        container_name: main
        hostname: main
        build:
            context: .
            dockerfile: dockerfile
        ports:
            - "3000:3000"
        volumes:
            - .:/app
            # - /main/node_modules
            # - /main/vendor
        command: sh -c "php artisan key:generate && php artisan passport:keys && npm run all"
   
# networks:
#     default:
#         external:
#             name: nginxrpgateway_default
